### ISSUE TITLE
Overlay "appmenuPrimaryPane" without duplicating overlay code - populate NTT's menuitem at run-time in appmenu

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#101]
Overlaying with empty `menupopup` like below, and cloning the `menupopup` from `<menu id="nightly-menu">` would avoid overlay code duplications - see 59bccf64fb19 or even Issue #100.

```
    <vbox id="appmenuPrimaryPane">
      <menu id="nightly-appmenu" label="Nightly Tester Tools" insertafter="appmenu_webDeveloper">
        <menupopup />
      </menu>
    </vbox>
```

**Comment by whimboo** [comment]
This is all XUL and doesn't exist anymore with the rewrite.
