### ISSUE TITLE
Re-introduce Options dialog

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#106]
Options dialog was transformed to Titlebar Custiomization dialog and extracted into Nightly Tester Tools menuitem in commit https://github.com/mozilla/nightlytt/commit/5aa61340c5b8.

For example, the preference for Issue #92 could be included. Another checkbox for [`nightly.logging`](https://github.com/mozilla/nightlytt/blob/788d3fce7015/extension/modules/Logging.jsm#L72) could be also included.

**Comment by whimboo** [comment]
Options for extensions based on the WebExtension API are located in the addons manager. I don't think we have other options here.
