### ISSUE TITLE
[customize-titlebar] Unable to revert changes if variables was added by clicking on the tree

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#108]
The [comment](http://forums.mozillazine.org/viewtopic.php?p=12448385#p12448385) below, from **tonymec** describes the problem:

> nightlytt-3.4pre-issue-31-5e0db21c951c.xpi
> 
> Clicking an element line adds it to the input value. The title is immediately updated, even before I close the dialog by clicking "OK". Clicking "Cancel" instead in the dialog does not undo these changes, IOW the "Cancel" button is actually an "OK" button.
> The fact that browser.preferences.instantApply is set to false (which is not the default on Linux) in about:config doesn't prevent this behaviour.

And the [root cause](http://forums.mozillazine.org/viewtopic.php?p=12449147#p12449147) is:

> Ohh, this is a "known issue".
> Introduced in harth's commit 3bb023c1c4da!
> 
> "OK" and "Cancel" button works, but clicking on the tree to add variables to title **[also applies the changes](https://github.com/mozilla/nightlytt/blob/788d3fce7015/extension/chrome/content/titlebar/customize.js#L154)** immediately.
> "Cancel" button reverts only the changes only if You edit the textbox by hand!

**Comment by whimboo** [comment]
With the rewrite of the extension this works fine!
