### ISSUE TITLE
Cleanup unused nightlyApp.storedTitle (practically from browser.js)

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#111]
_From Pull #104_.

**xabolcs** [commented](https://github.com/mozilla/nightlytt/pull/104#discussion_r2076304):

> In commit [`3bb023c1c4da`](https://github.com/mozilla/nightlytt/commit/3bb023c1c4da#L1L70) **harthur** moved away from this initial, `storedTitle` related implementation of "title computing".
> After that `nightly.variables.defaulttitle` became a getter. Therefore assigning a value to it is a no-op.
> Or just a warning in the Error Console if `javascript.options.strict` is enabled:
> 
>   TypeError: setting a property that has only a getter
> 
> Examining the commit, You could get the resolution that `nightlyApp.storedTitle` isn't used in the new version.
> So it can be removed. (And should be removed in `browser.js`!)

**Comment by whimboo** [comment]
This code doesn't exist anymore with the rewrite of the extension.
