### ISSUE TITLE
Decide about Imgur API version 3

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#114]
See [documentation](http://api.imgur.com/)!

> ...
> The Imgur API is a RESTful API based on HTTP requests and XML or JSON(P) responses. If you're familiar with the APIs of Twitter, Amazon's S3, del.icio.us, or a host of other web services, you'll feel right at home.
> 
> This version of the API, version 3, uses OAuth 2.0. This means that all requests will need to be encrypted and sent via SSL/TLS to `https://`. It also means that you need to [register](http://api.imgur.com/oauth2/addclient) your application, even if you aren't allowing users to login.
> ...

The Question is: should NTT support imgur API v3?

**Comment by whimboo** [comment]
With the rewrite we removed the screenshot feature because it's part of Firefox now.
