### ISSUE TITLE
Determine nightly.templates.buildid default preference at Application startup

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#127]
Mozilla Applications in Ubuntu and Debian (and maybe in other distros) do not have `SourceStamp` key in the `application.ini` file.
The new `${CSet}` string (introduced in v3.4 by #65) in the build ID doesn't have an added value for those Users:

> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:17.0) Gecko/17.0 Firefox/17.0 ID:20121119183901 CSet: Undefined

Revert it back for them to the v3.3 value!

**Comment by whimboo** [comment]
For the rewrite of the extension we have to rely on what the WebExtension API is giving us.  So I think this is not necessary anymore.
