### ISSUE TITLE
Anonymize nightly and nightlyApp implementations to allow Components.* (Cc, Cu, ...) shortcuts be used

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#128]
[From](https://github.com/mozilla/nightlytt/pull/82#discussion_r3731249) pull #82 for _issue #52_:

**whimboo** wrote:

> We have an inconsistency here how we use Cc and Ci regarding their short and long names. If you feel fine please make it shorter here.

**xabolcs** wrote:

> I see no inconsistency here reagrding to Cx shortcuts.
> Please note that nightly.js doesn't have those shortcuts!

My proposal is that to implement `nightly` and `nightlyApp` as [anonymous function](http://mesquilla.com/2011/09/08/avoiding-namespace-leaks-in-event-handlers/comment-page-1/#comment-2958)s,
and export the defined variable to `window` like below:

```
(function() {
  const {Cc: classes, Ci: interfaces, Cu: utils, Cm: manager} = Components;

  var nightly = {

    variables: {
      _appInfo: null,
      get appInfo() {...}
    },

  ...
  }

  window.nightly = nightly;
  window.addEventListener("load", nightly.init, false);
  window.addEventListener("unload", nightly.unload, false);

})();
```

**Comment by whimboo** [comment]
This only worked for the old legacy extension.
