### ISSUE TITLE
[l10n] Create locales and upload to Babelzilla

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#142]
Create localization templates, and register them in `chrome.manifest`.
Upload to Babelzilla after that.

But first of all, do a poll about which locales should be included.
Or simply include the top 3 from [AMO](https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/statistics/?last=90). :-)

**Comment by whimboo** [comment]
Localization will be different with the rewrite of the extension. So I don't think this is necessary anymore.
