### ISSUE TITLE
[screenshot] Remember last selected filetype in filepicker

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#148]
From the pull request #146:

**whimboo** wanted to switch default to `jpg`:

> I would default to jpg given that it is smaller as png, and the default encoding keeps it in a quite good quality.

**xabolcs** proposed:

> > ... given that it is smaller as png ...
> 
> This is [not always](https://en.wikipedia.org/wiki/Portable_Network_Graphics#Comparison_to_JPEG) true. Personally I prefer png for screenshots.
> 
> Instead changing defaults I propose to extend NTT's screenshot functionality **to remember** the selected extension.
> Thouhgts?

**Comment by whimboo** [comment]
We removed screenshots given that it is a core feature of Firefox now.
