### ISSUE TITLE
Make ready to (someday) remove calls to deprecated methods

### ISSUE THREAD

**Issue by tonymec** [mozilla/nightlytt#161]
See https://addons.mozilla.org/en-US/developers/addon/nightly-tester-tools/file/230591/validation#compatibility-tests for details.

Those calls to deprecated methods are necessary for support of "earlier" Gecko/Toolkit versions, but the fact that they are deprecated means that their removal is foreseen in some future version of Firefox (and presumably Thunderbird and SeaMonkey too).

I don't have a ready-made solution to this conundrum.

**Comment by xabolcs** [comment]
- [ ] drop all fallback code prior Gecko 39.0
- [ ] use all the new feature which introduced in Gecko 39.0 or earlier and is still alive

**Comment by tonymec** [comment]
OK. AFAIK the "oldest" browser still at the "stable release" state is SeaMonkey 2.40 (based on Gecko 43.0) and even that will be abandoned as soon as SeaMonkey 2.45 (based on Gecko 48.0) is ready for release. Hopefully soon, since 2.45 tinderbox-builds are aleady available, but en-US only AFAIK.

**Comment by whimboo** [comment]
Correct. I think for now it is fine to remove all fallback code pre Gecko 43. I think that should be most of all the fallback code we have from the old pre 4.0 days.

**Comment by xabolcs** [comment]
> ... fallback code pre Gecko **43**. I think that ...

`43` is just a typo? If not, then an another `minVersion` bump is necessary.

**Comment by whimboo** [comment]
Correct. Just a typo. Should have been 39.

**Comment by xabolcs** [comment]
FYI [Firefox 39 for developers][1].


[1]: https://developer.mozilla.org/en-US/Firefox/Releases/39

**Comment by whimboo** [comment]
The rewrite of the extension got rid of all the old (and unused) code.
