### ISSUE TITLE
Basic support for Nightingale

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#165]
Songbird is [discontinued](http://slashdot.org/submission/2728691/poti-creators-of-the-songbird-media-player-are-calling-it-quits) [since June 28, 2013](https://web.archive.org/web/20130913155351/http://blog.songbirdnest.com/you-gotta-know-when-to-fold-em/). It's open source alternative is [Nightingale](http://getnightingale.com/).
We should support it.

**Comment by whimboo** [comment]
Not sure if that project is still active or not, but once they support webextensions, we can see again if something is broken.
