### ISSUE TITLE
Add NTT submenu to Mail-Compose "Tools" menu

### ISSUE THREAD

**Issue by tonymec** [mozilla/nightlytt#167]
I propose to add a submenu, or at least a menuitem (depending on what is deemed useful) in the Tools menu for the SeaMonkey or Thunderbird mail-compose window. _(I don't know whether the chrome URL is the same for both.)_

Not very important, and we might not want to make it identical to the Browser submenu — I think some items would be irrelevant.

One menuitem which I think **is** relevant is "Insert Build ID" though perhaps with a different wording (an email message could be thought of as one big textbox but people usually don't think like that). Maybe "Insert Build ID into Message" (not "into email" since it could be an email message or an NNTP news message).

It is true that the user-agent string is already present as part of the message headers, but:
- Most headers (including the User-Agent header) are normally hidden when reading the message
- Build ID and changeset IDs are not included anyway.

**Comment by whimboo** [comment]
I don't think that this is a feature which will really be used. Closing for now.
