### ISSUE TITLE
Make NTT ready for E10s (multi-process)

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#170]
For example you are unable to insert build ID / extension list into textbox, because the focus isn't detected.

**Comment by whimboo** [comment]
Sadly we have to move this to our 3.9 schedule.

**Comment by whimboo** [comment]
So what we basically need now is a total rewrite of the extension to survive upcoming changes with Firefox 57. By that version all old-style extension won't work anymore.

I will file a new issue to specifically cover this part.

**Comment by xabolcs** [comment]
>... By that version all old-style extension won't work anymore. ...

I'm wondering which features of NTT could survive.
Looking forward for that new issue.

**Comment by whimboo** [comment]
I filed as issue #235.
