### ISSUE TITLE
Sort variables alphabetically in customize.js

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#172]
See [review comment][1]!

[1]: 171#discussion-diff-18148430

**Comment by ritwikmishra** [comment]
Hello everyone please tell me how to proceed in order to solve this bug? I think the steps are [1] fork the repo [2] find contribute.js [3] just sort the variables alphabetically
But my first doubt is "Where is contribute.js?"

**Comment by xabolcs** [comment]
You need to find `customize.js` not <del>`contribute.js`</del>! :)

[It][1] is on path `extension/chrome/content/titlebar/customize.js`!

After step `2`, and before step `3` (start coding) please open a new branch, and working on that. Some talking name would good for it, for example `issue-172`, `sort-titlebar`, ...

[1]:https://github.com/mozilla/nightlytt/blob/master/extension/chrome/content/titlebar/customize.js#L86-105

**Comment by ritwikmishra** [comment]
I am sorry to bother you with such a stupid doubt, I opened the "review comment" on this page and found the path. I have branched offf with "issue-172" and found `customize.js` I think the tabs which need to be sorted are from `line 86` to `line 105`
If the tabs are static I think they can be sorted manually, isn't it? All the variables can be placed in an array and then sorted but is there a need for it?

**Comment by xabolcs** [comment]
Hello! :)

It's no problem!

The source code (the `customize.js`'s `L86-L105` range) itself should be sorted! For readability and for coding style. 

There are no stupid question!

**Comment by ritwikmishra** [comment]
I followed all the steps (made a branch named "issue-172" also) and sorted the `L86-L105`. Should create a pull request now?

**Comment by xabolcs** [comment]
> Should create a pull request now?

Yes, that's the next step!

**Comment by ritwikmishra** [comment]
Does it mean I patched the problem and fixed the bug?

**Comment by xabolcs** [comment]
You have provided a patch in PR#183, that resolves the problem. That PR should be reviewed and if it got accepted, it will land.

After that landing would this issue get closed.

**Comment by xabolcs** [comment]
Fixed by the referencing commit 6f1c7e88ab9a4c35c8d44a3cd8cab8b170656112.

Thanks @ritwikmishra for your contribution!
