### ISSUE TITLE
Update development section of readme to get rid of Bugzilla content

### ISSUE THREAD

**Issue by whimboo** [mozilla/nightlytt#181]
Already a while ago we got rid of Bugzilla and handle our bugs and reviews on Github. Sadly we missed to update the readme et all for this move. We should do it to make it easy enough for contributors to help us, and find the appropriate tasks to work on.

**Comment by UtiluMark** [comment]
@whimboo I've created PR #213 to fix this. The links to bugzilla.mozilla.org are also mentioned in issue #203.

**Comment by whimboo** [comment]
PR #213 got merged.
