### ISSUE TITLE
supporting Pale Moon

### ISSUE THREAD

**Issue by roytam1** [mozilla/nightlytt#184]
Change of chrome.manifest is needed. Adding:

```
# Pale Moon chrome
overlay      chrome://browser/content/browser.xul                     chrome://nightly/content/browserOverlay.xul              application={8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}

```

**Comment by xabolcs** [comment]
Thanks @roytam1!

Do you think this would be enough to help for [fady005][1] at AMO?


[1]: https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/reviews/674718/ "Not working"

**Comment by xabolcs** [comment]
Hmm, it helps! Thanks again.

**Comment by xabolcs** [comment]
@whimboo 

Should we duplicate `browser.(js|xml)` to it's Palemoon files (e.g. `palemoon.(js|xml`)?
`browsee.*` currently works for Palemoon, so this could be a one liner fix.

**Comment by whimboo** [comment]
Hm, good question. Maybe that's a good idea to duplicate the file. Just in case they are making changes to their browser in the future. So I assume the one-line change is for the manifest?

Thanks for having a look into this.

**Comment by xabolcs** [comment]
Yes, if I update `chrome.manifest` with the proposed change from @roytam1, PaleMoon support is done. :)

No extra changes are needed for `browser.*`.

IMHO it's a good idea to duplicate, because PaleMoon doesn't merged Customizable UI and still have an AppMenu for example.
My downloaded PaleMoon is 25.2.1 and based on Gecko 31.9: 
`Mozilla/5.0 (Windows NT 6.1; WOW64; rv:25.2) Gecko/20150122 Firefox/31.9 PaleMoon/25.2.1 ID:20150122013745 CSet: Undefined`

**Comment by xabolcs** [comment]
It would be nice to disable repo related features. Like this `CSet: Undefined`.

**Comment by whimboo** [comment]
How does the application.ini and platform.ini file of palemoon look like?

**Comment by xabolcs** [comment]
`application.ini`:
``` ini
; This file is not used. If you modify it and want the application to use
; your modifications, move it under the browser/ subdirectory and start with
; the "-app /path/to/browser/application.ini" argument.
[App]
Vendor=Moonchild Productions
Name=Pale Moon
Version=25.2.1
BuildID=20150122013745
ID={8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}

[Gecko]
MinVersion=25.2.1
MaxVersion=25.2.1

[XRE]
EnableProfileMigrator=1
EnableExtensionManager=1

[Crash Reporter]
ServerURL=
Enabled=0
```

`platform.ini`:
``` ini
[Build]
BuildID=20150122013745
Milestone=25.2.1
```

**Comment by whimboo** [comment]
Given that we share the variables it might not be that easy. I think it is ok to leave all of them and users of Palemoon have to accept `undefined`.

**Comment by xabolcs** [comment]
`undefined` is OK to me, but this `CSet: Undefined` comes from default pref `nightly.templates.buildid`.
I propose an installtrigger to strip `CSet` out from template pref.

Interestingly PaleMoon have no built-in install trigger like "install-event-fired" like Firefox.

> My downloaded PaleMoon is 25.2.1 and based on Gecko 31.9

OMG, this is only for UserAgent... It has Gecko version 25.2.1.

**Comment by roytam1** [comment]
> OMG, this is only for UserAgent... It has Gecko version 25.2.1.

I doubt it. It seems to be 24 ESR with custom fixes. And it reports to addons.mozilla.org with version 24.9.

**Comment by xabolcs** [comment]
> I doubt it. It seems to be 24 ESR with custom fixes. And it reports to addons.mozilla.org with version 24.9.

Thanks for the clarification.

**Comment by whimboo** [comment]
I wouldn't make it that complicated. For this issue just add the necessary files and changes. In a follow-up issue we might want to add the feature to set default variables for different applications. How does that sound?

**Comment by xabolcs** [comment]
> How does that sound?

Sounds good! Thanks!

**Comment by whimboo** [comment]
So once PaleMoon supports addons based on the WebExtension API it should work. We could revisit later if something is broken.
