### ISSUE TITLE
enble "Open pushlog between last and current builds" on beta releases

### ISSUE THREAD

**Issue by Cai0407** [mozilla/nightlytt#185]
"Open pushlog between last and current builds" menu is not appeared on beta releases.
Here is the patch to show this menu on Firefox/Thunderbird/SeaMonkey beta releases.

    diff -r -U 3 content/browser.js content-mod/browser.js
    --- content/browser.js	2013-10-24 01:51:02.000000000 +0900
    +++ content-mod/browser.js	2014-06-29 03:26:26.536673600 +0900
    @@ -4,7 +4,7 @@
     
     var nightlyApp = {
     
    -repository: ['mozilla-central','mozilla-aurora'],
    +repository: ['mozilla-central','mozilla-aurora','mozilla-beta'],
     
     storedTitle: document.documentElement.getAttribute("titlemodifier"),
     
    diff -r -U 3 content/messenger.js content-mod/messenger.js
    --- content/messenger.js	2013-10-14 22:29:56.000000000 +0900
    +++ content-mod/messenger.js	2014-06-29 03:26:47.267819000 +0900
    @@ -4,7 +4,7 @@
     
     var nightlyApp = {
     
    -repository: ['comm-central','comm-aurora'],
    +repository: ['comm-central','comm-aurora','comm-beta'],
     
     savedTabmailSetDocumentTitle: null,
     tabmailSetDocumentTitle: null,
    diff -r -U 3 content/nightly.js content-mod/nightly.js
    --- content/nightly.js	2013-10-24 01:51:02.000000000 +0900
    +++ content-mod/nightly.js	2014-06-29 03:33:20.282628200 +0900
    @@ -65,7 +65,8 @@
       
       return isNightlyRepo
         && (nightly.variables.platformversion.indexOf("pre") != -1 || 
    -        nightly.variables.platformversion.indexOf(".0a") != -1);
    +        nightly.variables.platformversion.indexOf(".0a") != -1 || 
    +        nightly.variables.platformversion.indexOf(".0") != -1);
     },
     
     /**
    diff -r -U 3 content/suite.js content-mod/suite.js
    --- content/suite.js	2013-10-14 22:29:56.000000000 +0900
    +++ content-mod/suite.js	2014-06-29 03:27:01.924249700 +0900
    @@ -4,7 +4,7 @@
     
     var nightlyApp = {
       
    -repository: ['comm-central','comm-aurora'],
    +repository: ['comm-central','comm-aurora','comm-beta'],
     
     _oldUpdateTitlebar: null,
     debugQATitleModifierWorkaround: null,

**Comment by xabolcs** [comment]
Nice!

**Comment by xabolcs** [comment]
Closing this as it moved to PR #197, and the original issue is #51.
