### ISSUE TITLE
Please port ${PlatformChangeset} from beta to release

### ISSUE THREAD

**Issue by tonymec** [mozilla/nightlytt#190]
I hope i'm not asking for something which has already been done during the month or two while I had no Internet connection.

Last I looked, the customization variable `${PlatformChangeset}`, which gives the mozilla-central (or -aurora, -beta, -release) Mercurial changeset on applications like Thunderbird and SeaMonkey, where `${Changeset}` is the comm-central (or -aurora, -beta, -release) changeset, was available for customization into **nightly.templates.title** and **nightly.templates.buildid** in the "beta" version 3.7pre20131013 but not in the "release" version.

This feature is useful for anyone using NTT on Thunderbird or SeaMonkey, and AFAIK no one has complained about it. I use it, and I have occasionally mentioned it at the SeaMonkey Status Meeting (on alternate Tuesdays at ircs://irc.mozilla.org/seamonkey at 14:00 CET/CEST i.e. local time from Spain to Poland).

I don't remember exactly which git commits implement it (or I would have opened a pull request) but they are somewhere in the beta branch. I hope @xabolcs remembers what they are.

Please port them to the `master` branch.

**Comment by xabolcs** [comment]
Hi @tonymec!

There is no need to rerequest this feature. GitHub doesn't have a voting feature, but you could always comment on any issue! :)

The issue for `${PlatformChangeset}` is at #129, the PR is at #137.

PR review is stucked, I could continue addressing comments if anybody would have the time to review.
Sadly @whimboo is currently the only peer.


Please continue the talk in #129! Closing this.
