### ISSUE TITLE
If xabolcs/nightlytt/branch-issue-129-platform-changeset is regarded as "not yet ready to be merged into mozilla/nightlytt/master", then please consider publishing a new "development" build at AMO.

### ISSUE THREAD

**Issue by tonymec** [mozilla/nightlytt#202]
I notice that the "development build" available at AMO is at version 3.7pre20131013, i.e., built a little more than 2 years ago.

I also notice that xabolcs/nightlytt/branch-issue-29-platform-changeset has recently (November 10 IIUC) been the target of merges from mozilla/nightlytt/master.

Putting two and two together, I get only three-and-a-half, which leads me to ask: Shouldn't this new version be uploaded at AMO? Or better yet, would it be possible to merge it back into the master branch of the Mozilla repo? (Or are there too many merge conflicts for that?)

**Comment by xabolcs** [comment]
I'm going to build and release a new beta build. :+1:

**Comment by xabolcs** [comment]
I'll force update the beta branch to step over the long but useless history.

**Comment by xabolcs** [comment]
Beta version [`3.9pre20160829`][1] is on AMO.


[1]: https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/versions/3.9pre20160829
