### ISSUE TITLE
Compatibility error: FUEL no longer supported in Fx47

### ISSUE THREAD

**Issue by tonymec** [mozilla/nightlytt#205]
The automatic periodic compatibility check run by AMO found 4 Fx47-related errors in NTT 3.7, all for "FUEL library no longer supported, use add-on SDK instead." NTT developers listed as such with AMO can see the report at https://addons.mozilla.org/en-US/developers/addon/nightly-tester-tools/validation-result/532318

Of course, such an error is bogus if it concerns a snippet of code which is only executed on Firefox 46 and lower; and OTOH the SDK has its own problems, one of them being that AFAIK only Firefox (not SeaMonkey or Thunderbird) supports it fully.

I don't know add-on coding well enough to check myself if the errors are indeed errors, and what to do if they are. (If they aren't, an NTT developer known as such by AMO can explicitly set the maxVersion to 47.*, 49.0a1 or whatever; and if they are but can be satisfactorily fixed, a fixed version should be uploaded with a "high enough" maxVersion, and undergo "full verification" just like the previous versions did.)

**Comment by xabolcs** [comment]
**offtopic:**
Latest AMO version of NTT has a few broken feature on top of this FUEL stuff.

I wouldn't like to upload a version to AMO without fixing those.

**Comment by xabolcs** [comment]
@tonymec, thanks for filing this issue! :)

**Comment by xabolcs** [comment]
`nightlyApp` in `messenger.js` and `suite.js` use `Application`, which isn't [`FUEL`][1] but [`STEEL`][2] and [`SMILE`][3].

Seems like nothing to do here.

[1]: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Toolkit_API/FUEL
[2]: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Toolkit_API/STEEL
[3]: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Toolkit_API/SMILE

**Comment by whimboo** [comment]
We should get this into the next release which we might want to release soon. I would propose doing smaller releases for faster cycles.

**Comment by xabolcs** [comment]
@whimboo, what do you think, how could this issue fixed?

**Comment by whimboo** [comment]
I haven't actually worked with FUEL so far. Does it mean that all usages of `Application` are the problem? Where is that element defined or included?

**Comment by xabolcs** [comment]
Not all, but the Firefox usages of `Application` are the problem.

Did you see my [comment][1]?

[1]: https://github.com/mozilla/nightlytt/issues/205#issuecomment-218740920

**Comment by whimboo** [comment]
No, Firefox itself doesn't use Application anymore, it's NTT which still relies on it. Here a reference of what FUEL was able to deliver:

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Toolkit_API/FUEL

What we should do is to kill each line which is using `Application` and should make use of `Services.jsm` instead. I assume there should be equivalents available for all members of Application.

**Comment by xabolcs** [comment]
I mean `browser.js`' usages of `Application`.

**Comment by whimboo** [comment]
You mean `nightly.js`? I cannot find the usage of `Application` in `browser.js`. So it would be good to post a listing of all its usage across our code. I could then propose alternatives to use.

**Comment by xabolcs** [comment]
Ok, You really didn't get my [comment][1]. :)
Here is your `Application` usage [search][2].

[1]: https://github.com/mozilla/nightlytt/issues/205#issuecomment-218740920
[2]: https://github.com/mozilla/nightlytt/search?utf8=%E2%9C%93&q=Application+language%3AJavaScript

**Comment by whimboo** [comment]
Your referenced comment didn't say anything about `nightly.js` which is used for Firefox. The comment only covers SeaMonkey and Thunderbird. Also it's still not clear to me which `browser.js` file you mean which makes use of `Application`. I cannot find any reference, really.

**Comment by xabolcs** [comment]
`nightly.js` is included in all supported application. `browser.js`, `messenger.js` and `suite.js` is application specific files.
Therefore NTT uses only `nightly.js` and `browser.js` under Firefox. And in this context there area no reference to `FUEL`, as you found out in your last comment.

**Comment by whimboo** [comment]
What's up with https://github.com/mozilla/nightlytt/blob/master/extension/chrome/content/nightly.js#L536 then?

**Comment by xabolcs** [comment]
> What's up with

Ouch! Sorry! I searched with GitHub. :-1:

**Comment by whimboo** [comment]
I see. My feeling is do not trust its search feature. A local `grep` is always better.

So it means we definitely have to get something fixed here. Good to see that we are on the same page now.

**Comment by whimboo** [comment]
Hello @xabolcs! A long time has passed by. I wonder if you would be able to get this bug fixed. It meanwhile makes the add-on partly unusable. Please let us know. Thanks!

**Comment by xabolcs** [comment]
I didn't get a time slice for this yet.

But taking this, for now.

**Comment by whimboo** [comment]
PR #206 got merged. Thanks @xabolcs!
