### ISSUE TITLE
Release NTT version 3.8

### ISSUE THREAD

**Issue by whimboo** [mozilla/nightlytt#207]
When all the dependencies have been fixed we will release a new version. 

Steps to do:
- [x] Update changelog
- [x] Bump version to `3.8` and update [application versions](https://addons.mozilla.org/pages/appversions/)
- [x] Create `v3.8` tag on the landed commit
- [x] Release to AMO

**Comment by whimboo** [comment]
@xabolcs: while bumping min/max versions I noticed that the latest release of  Seamonkey was based on:

> 43.0 	2.40 	14. März 2016[25] 	Als Basis wird die Mozilla-Firefox-Version 43.0 verwendet.

Would the changes we have made be incompatible with it, given that I said Firefox 45? Also we should remove Songbird from our list, given that the project is dead since 3 years.

**Comment by xabolcs** [comment]
Only [`AppConstants.jsm`][2] was introduced.
> `AppConstants.jsm` was brought to you by [Bug 1124503][3] with milestone `mozilla39`.


[2]: http://mxr.mozilla.org/mozilla-central/source/toolkit/modules/AppConstants.jsm
[3]: https://bugzilla.mozilla.org/show_bug.cgi?id=1124503 "Bug 1124503 - move AppConstants.jsm to toolkit"

**Comment by UtiluMark** [comment]
In Utilu Mozilla Firefox Collection, NTT is used to display the version number in the titlebar of Firefox 4.0.1 and higher. If a change breaks the compatibility with older versions of Firefox, that would mean having to include multiple NTT versions. Is that really necessary?

**Comment by xabolcs** [comment]
In the long term NTT would be restartless and would support the last (or sometimes the last two) version of ESR Firefox.

**Comment by whimboo** [comment]
Why Firefox 4.0.1? You know that this version is not only outdated and unsupported but also full of security issues these days. Absolutely no-one should use such an old version anymore. That said, I do not see why add-ons should keep compatibility way down this road.

**Comment by whimboo** [comment]
> AppConstants.jsm was brought to you by Bug 1124503 with milestone mozilla39.

That's indeed way better! So we can keep support for some SeaMonkey releases. Thanks.

**Comment by UtiluMark** [comment]
@whimboo Utilu Mozilla Firefox Collection contains all major versions of Firefox and uses NTT to display the version number in the titlebar for Firefox 4.0.1 up to the latest Nightly. This is useful for web developers, so they can see how their websites look when rendered using different versions. If a necessary change in NTT breaks the compatibility with older versions of Firefox, multiple NTT versions will be included, but if that can be avoided easily that would be preferred.

**Comment by whimboo** [comment]
PR #208 just got merged.

Tagged as 3.8:
https://github.com/mozilla/nightlytt/tree/v3.8

**Comment by whimboo** [comment]
Uploaded the XPI to AMO for review:
https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/versions/?page=1#version-3.8

I will keep this issue open until it has been reviewed.

**Comment by whimboo** [comment]
Version 3.8 has been released! Thank you all for the help, it was a long overdue release!
