### ISSUE TITLE
Make use of crashme-simple (without binaries)

### ISSUE THREAD

**Issue by whimboo** [mozilla/nightlytt#210]
It might be that our 3.8 release of NTT will not pass review due to the contained binaries from the crashme extension. What we should do is to rely on the new [crashme-simple](https://github.com/luser/crashme-simple) extension which only makes use of ctypes.

I wonder if we even can completely get rid of the bundled version, and auto-detect that feature.

**Comment by xabolcs** [comment]
+1 for the auto-detect feature.
And a menuitem to AMO site if not detected.

**Comment by whimboo** [comment]
I would suggest that we use the same submenu item which is called "Crash me!". We only make it dynamic. In the case of crash me simple not installed, we could say "Install add-on from AMO" or such.

As a note, the new version of crashme can also crash the content process only, which would be very useful as testing ground for developers in e10s mode.

**Comment by whimboo** [comment]
I currently need crashme-simple while working on [bug 1299216](https://bugzilla.mozilla.org/show_bug.cgi?id=1299216). So I will take this issue, and for now simply replace the old version with the new binary-less one. An auto-detect feature we can do later. Thing is that the extension only has toolbar buttons, but it would be nice to have access via the menu too.

**Comment by xabolcs** [comment]
Taking back to milestone `3.9` as @whimboo started to work on it! :+1:

**Comment by xabolcs** [comment]
> ... An auto-detect feature we can do later. ...

Please file an issue for that! Thanks!

**Comment by whimboo** [comment]
PR #217 got merged.
