### ISSUE TITLE
Pastebin requires the use of the new api

### ISSUE THREAD

**Issue by Endor8** [mozilla/nightlytt#211]
If you try to upload about:support to pastebin, from the context menu, you got only the message:
THIS API HAS BEEN DISABLED. Please use Pastebin's new API. http://pastebin.com/api.
Please fix this. 
Thank you.

**Comment by xabolcs** [comment]
Thanks for reporting!

**Comment by xabolcs** [comment]
See issue #86! It has already patch, so it would be fixed in the next release , hopefully.

I'm closing this, because of duplicate.
