### ISSUE TITLE
Nightly Tester Tools 3.8: Error: ReferenceError: Cu is not defined

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#215]
[Ouch][1]!
```
Timestamp: 08/28/2016 08:30:47 PM
Error: ReferenceError: Cu is not defined
Source File: chrome://nightly/content/suite.js
Line: 100
```

Bad copy-paste!

[1]: https://github.com/mozilla/nightlytt/blob/v3.8/extension/chrome/content/suite.js#L100 "ReferenceError: Cu is not defined"

**Comment by xabolcs** [comment]
Opening  a hotfix branch `3.8-hotfix` and landing this and release as `3.8.1`?

**Comment by UtiluMark** [comment]
In https://github.com/mozilla/nightlytt/commit/f08b18fea1021eac835405b50b7ed0635f0b015a (#206) that same line 
> Cu.import("resource://gre/modules/AppConstants.jsm");

was added a second time as line 88 in [chrome/content/messenger.js](https://github.com/mozilla/nightlytt/blob/v3.8/extension/chrome/content/messenger.js#L88)

**Comment by xabolcs** [comment]
Ouch! Thanks!

**Comment by whimboo** [comment]
Which applications are affected specifically by this bustage? Is it only SeaMonkey or also Thunderbird? I would suggest we get landed those patches which are close to be ready and simply release a version 3.9. We should also make sure to get tests added.

**Comment by xabolcs** [comment]
Didn't test Thunderbird, but it should die too. SeaMonkey died.

**Comment by whimboo** [comment]
PR #216 got merged. We should check what else we can merge into the 3.9 release.

**Comment by whimboo** [comment]
Looks like the fix as landed here was not enough to fix NTT for SeaMonkey. I will file a new issue.
