### ISSUE TITLE
Extension is not marked as compatible with Multi Process

### ISSUE THREAD

**Issue by whimboo** [mozilla/nightlytt#228]
From AMO while pushing the new release:

> Warning: Your extension is not marked as compatible with Multi-Process Firefox and may not work in future versions of Firefox. Please review it, make changes if needed and set em:multiprocessCompatible to true in install.rdf if it's compatible. See https://developer.mozilla.org/docs/Mozilla/Add-ons/Working_with_multiprocess_Firefox for more information.

**Comment by whimboo** [comment]
We have to fix this ASAP because NTT doesn't work anymore in latest Nightly. All addons which are not marked as multi-process compatible are disabled. Given that NTT worked fine so far with e10s enabled, we should simply add this option to the install.rdf.

I will get this added.

**Comment by xabolcs** [comment]
Fix commited as b4e77b9319b93a522005602c44e58d2118bb1c17.
