### ISSUE TITLE
No titlebar customization in SeaMonkey 2.54a1 20170807003001

### ISSUE THREAD

**Issue by tonymec** [mozilla/nightlytt#243]
Several entry points were removed tonight, other names have to be used instead, see https://groups.google.com/forum/#!topic/tb-planning/lbQIuLNv_2s for details.

No titlebar customization in NTT 3.9pre.20160829 (home-built with ${PlatformChangeset} etc. included).

ChatZilla is broken in an even worse way. I didn't check what else was broken and hurried the hell out to yesterday's nightly.

**Comment by tonymec** [comment]
P.S. Tested again in the next nightly, 20170808003001.

"Customize Titlebar" dialog, toolbar button and Tools submenu are still present. Clicking the button to insert the build ID etc. to a textbox toes nothing.

First known bad:
20170807003001
https://hg.mozilla.org/comm-central/rev/eeb9fb0aac793072b54e7dec4b75988b6611133b
https://hg.mozilla.org/mozilla-central/rev/bb8de16ce00c

Last known good:
20170806003001
https://hg.mozilla.org/comm-central/rev/7067b32d6404e0778ea00efa0b1da6c857a56e60
https://hg.mozilla.org/mozilla-central/rev/933a04a91ce3

**Comment by whimboo** [comment]
This is all about gecko 57 work and expected to fail. There is absolutely nothing we can and want to do here for the legacy NTT extension.
