### ISSUE TITLE
incompatible with Firefox 57

### ISSUE THREAD

**Issue by netllama** [mozilla/nightlytt#244]
Starting in November 2017 (less than 3 months from today), Firefox 57 will only support extensions that are written to the WebExtensions standard.  This extension is currently incompatible.  

Are there plans to add support for Firefox57, or will this extension die?

**Comment by xabolcs** [comment]
This extension will die, as you know it, and will be rewritten as a webextension with minimal feature list.
See issue #235 for the details!
