### ISSUE TITLE
Cannot insert buildid into some text boxes

### ISSUE THREAD

**Issue by whimboo** [mozilla/nightlytt#249]
For example the search field on AMO doesn't allow me to paste in the buildid:

https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/

Whenever I try that I see the following message but without a reference to a file:

> Error: Could not establish connection. Receiving end does not exist.

@kyoshino can you please have a look?

**Comment by whimboo** [comment]
Btw. it also doesn't work for contenteditable elements.

**Comment by kyoshino** [comment]
Will figure out why.

**Comment by whimboo** [comment]
@kyoshino will you have the time to get this investigated/fixed? If not we might want to release the 4.0 version, and get this done for 4.1. I would just like to get the release out now that 57 is on beta. Thanks.

**Comment by kyoshino** [comment]
Sorry I'm late!! Looks like the AMO issue cannot be solved as reported as [Bug 1310082](https://bugzilla.mozilla.org/show_bug.cgi?id=1310082). Fixing the `contenteditable` issue now.

**Comment by whimboo** [comment]
That sounds good to me. Thank you for the update @kyoshino. I will review it soon.

**Comment by whimboo** [comment]
PR #253 got merged.
