### ISSUE TITLE
Promote to beta audience

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/nightlytt#255]
Looking at the features, nothing I see here seems specific to Firefox Nightly only. I suggest to rebrand this extensions from Nightly Tester Tools to Firefox Tester Tools and promote it at least to the beta audience. Adding some basic integration with Bugzilla can ease reporting bugs for beta users or even Firefox release users. That would be for a further discussion, what will or won't help the "new target audience".

**Comment by UtiluMark** [comment]
Since Nightly Tester Tools is also for other Mozilla applications like SeaMonkey and Thunderbird, I think using the name Firefox in it isn't a good idea.
Indeed it's not specific to Firefox Nightly or SeaMonkey Nightly or Thunderbird Nightly, but can also be useful in beta and final versions.

**Comment by MikkCZ** [comment]
Do you think it would be possible to eventually ship NTT WebExt with Firefox Nightly similar way like the Webcompat report extension is?

**Comment by whimboo** [comment]
No, there is barely support for this extension, and there are a couple of obstacles to take to become a system add-on.
