### ISSUE TITLE
Reopen closed tabs works in Incognito mode

### ISSUE THREAD

**Issue by srivkrnt** [mozilla/nightlytt#259]
The CLTRL+SHIFT+T shortcut works in icognito mode too and I guess it should not following the privacy in the incognito mode, the feature should be disabled .

**Comment by whimboo** [comment]
@srivkrnt you are reporting an issue for Firefox in the wrong bug tracker. I would suggest to file a bug in the following component: https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Tabbed%20Browser. Thanks.
