### ISSUE TITLE
panel-list-item background does not redraw when mouse out

### ISSUE THREAD

**Issue by magicp-github** [mozilla/nightlytt#260]
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0 ID:20171109220104

**Steps to reproduce:**
1. Launch the latest Nightly on Windows
2. Open NTT menu
3. Hover on menus

**Actual Results:**
panel-list-item background does not redraw when mouse out.
- reproduce on Win 7, 8.1 and 10.
- cannot reproduce on Ubuntu 17.04 and macOS 10.12.6

![ntt](https://user-images.githubusercontent.com/13914314/32646583-89deda32-c630-11e7-9c5b-8d090221fa7b.png)

**Comment by kyoshino** [comment]
I think it's a bug in Firefox, not in this particular extension.

**Comment by whimboo** [comment]
@magicp-github if you have a Bugzilla account, please get this filed under https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Layout%3A%20View%20Rendering. Let us know the bug number when you created the bug. Thanks.

Given that this is not an issue with NTT I will close it.
