### ISSUE TITLE
[customize-titlebar] Custom title bar does not work on blank pages/tabs

### ISSUE THREAD

**Issue by morenop3** [mozilla/nightlytt#265]
I am using this setting: ${Name} ${PlatformVersion}
My setting for "Preferences" -> "Home and new windows" and "New tabs" is: Blank Page

Just after run Firefox 62.0 I got a "Blank Page" and the title bar is: Mozilla Firefox
Just after run Firefox 52.9.0 ESR I got a "Blank Page" and the title bar is: Firefox 52.9.0

so it is working with Firefox 52.9.0 ESR but not with Firefox 62.0

Thanks

**Comment by whimboo** [comment]
Thank you for the report. Actually this is a known issue and tracked under #256.
