### ISSUE TITLE
Add open source software license

### ISSUE THREAD

**Issue by danielnazer** [mozilla/nightlytt#275]
This Mozilla repository has been identified as lacking a license. Consistent with Mozilla's [Licensing Policy](https://www.mozilla.org/en-US/MPL/license-policy/) an open source license should be applied to the code in this repository.

Please add an appropriate LICENSE.md file to the root directory of the project. In general, Mozilla's licensing policies are as follows:

-   Client-side products created by Mozilla employees or contributors should use the Mozilla Public License, Version 2.0 (MPL). 

-   Server-side products or utilities that support Mozilla products may use either the MPL or the Apache License 2.0 (Apache 2.0). 

In special cases, another license might be appropriate. If the repository is a fork of another repository it must apply the license of the original. Similarly, another license might be appropriate to match that of a broader project (for example Rust crates that Firefox depends on are published under an Apache 2.0 / MIT dual license, as that is the dual license used by the Rust programming language and projects).

Please ensure that any license added to the LICENSE.md file matches other licensing information in the repository (for example, it should match any license indicated in a setup.py or package.json file).

Mozilla staff can access more information in our Software Licensing Runbook – search for “Licensing Runbook” in Confluence to find it.

If you have any questions you can contact Daniel Nazer who can be reached at dnazer on Mozilla email or Slack.

OPENLIC-2023-01

**Comment by tonymec** [comment]
IIUC, Nightly Tester Tools is "a client-side product created and maintained by Mozilla contributors", therefore I suppose the MPL 2.0, or at the least (if the present license mentioned in the code is different) some open-source license including the MPL, should be used.

I am not developing nighlytt code anymore but I suppose the present developer(s) should take the appropriate steps.

Best regards,
Tony.

**Comment by xabolcs** [comment]
While it's not detected by Github, this repository uses MPL 2.0 since commit 1e3675e0f8dbc439cf877450ec59db2f9e61cc51.

@danielnazer should [that `LICENSE` file](https://github.com/mozilla/nightlytt/blob/v4.0/extension/LICENSE) be moved to the root of the repository to help such detection?
