### ISSUE TITLE
NTT customize title bar: add profile name variable

### ISSUE THREAD

**Issue by dan400man** [mozilla/nightlytt#277]
I use several Firefox profiles.  It would be helpful to have a variable ${ProfileName} to use in the custom title template.

**Comment by xabolcs** [comment]
#258 looks like this. What do you think, @dan400man ?

**Comment by whimboo** [comment]
Yes, I would close it as a dupe.

**Comment by dan400man** [comment]
I promise I searched before creating this issue!  I see 258 was created 6 years ago, so I guess I shan't hold my breath.
