### ISSUE TITLE
Renew Songbird support of titlebar customization to support SB 1.10.2

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#29]
I found some (portable) version of SB:
-   `1.4.3` - old stable
-   `1.7.3` - old stable
-   `1.10.2` - stable
-   `1.12.0a` - nightly

Titlebar customization doesn't work with `1.10.2` and up.
<del>If somebody could assign it to me (or flagging it as taken),</del> I happily dig into myself.

_FYI_ - [Songbird's Addon site](http://addons.songbirdnest.com/addon/122) with lot of comments

**Assigned** to @xabolcs.

**Comment by whimboo** [comment]
Not relevant for the rewrite of the extension anymore.
