### ISSUE TITLE
Make Tools More Discoverable

### ISSUE THREAD

**Issue by brianking** [mozilla/nightlytt#50]
This problem is more acute on Windows where we only have the Firefox menu button.

For me, the 'Nightly Tester Tools' menu is hard to get at. I propose:
1. We add a menu button to the navigation toolbar
2. We add a menu button to the add-ons bar

This can probably be done with the same code and then users can customise in which place they want it. I propose the add-ons bar by default, and we force show the bar once-only (so users can see it is new) after first install. This is similar to behaviour of an SDK add-on that adds a widget.

**Comment by whimboo** [comment]
The menu button is there now with the rewrite of the extension based on the WebExtension API.
