### ISSUE TITLE
Add pushlog feature to beta builds

### ISSUE THREAD

**Issue by whimboo** [mozilla/nightlytt#51]
I think that we should also add the pushlog feature for beta builds. Those people are also testers and for us it would be good to know what has been checked-in between beta releases.

**Comment by xabolcs** [comment]
This is the original beta pushlog issue.

A few years ago there was a timeout problem, now that was fixed.


Cc @whimboo, @Cai0407.

**Comment by xabolcs** [comment]
Fixed by the commit 60e1ba747c321fe7012a2793d77b495da5a6ac4e above.
