### ISSUE TITLE
Integrate User Agent Switching into Nightly Tester Tools

### ISSUE THREAD

**Issue by jds2501** [mozilla/nightlytt#68]
Allow users using nightly tester tools to perform user agent switching with desktop firefox builds to different user agent strings. Functionality would follow similar functionality to existing add-ons for user agent switching. A set of user agents that will need to be included should target areas such as:
- Webkit-based browsers on desktop and mobile (e.g. IPhone, Android Stock, Chrome)
- Gecko-based browsers on mobile (e.g. Fennec Native)

**Comment by whimboo** [comment]
Lets concentrate on specific use cases for Nightly testers. If there are extensions already out there which can change the UA, we don't have to re-invent the wheel.
