### ISSUE TITLE
copy about:support to pastebin menu entry is broken

### ISSUE THREAD

**Issue by whimboo** [mozilla/nightlytt#86]
When you try the above mentioned command you will get the following entry in the Error Console:

Error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWebNavigation.loadURI]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://global/content/bindings/browser.xml :: loadURIWithFlags :: line 156"  data: no]
Source File: chrome://browser/content/tabbrowser.xml
Line: 1358

**Comment by Endor8** [comment]
Since the pastebin issue is apparently well know since 2012 it would be
good if someone fix it finally. 
Thanks

**Comment by whimboo** [comment]
Yes, it bugs us for a while now. Lets try to get this fixed for the next 3.9 release.

**Comment by whimboo** [comment]
I think the patch is close to be ready to land. @xabolcs do you agree? Would be great to see it in the 3.9 release.

**Comment by xabolcs** [comment]
I do agree! I will have some minor questions in the PR.

**Comment by whimboo** [comment]
@xabolcs quick ping. Do you think you will have the time to work on this issue? If not we might want to get this pushed out to a later release so that we can finally get out 3.9. Thanks.

**Comment by whimboo** [comment]
It looks like that @xabolcs is not around those days. I will move out this issue to 3.10 then.

**Comment by whimboo** [comment]
We don't have the pastebin feature anymore in the rewrite of the extension and would have to find a new way of doing so.

**Comment by xabolcs** [comment]
Follow up issue is #251.
