### ISSUE TITLE
Change the old code to have consistent coding style

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#87]
Based on talk in [`#ateam`](http://logbot.glob.com.au/?c=mozilla%23ateam&s=13+Jun+2012&e=13+Jun+2012#c352554) We should update the codebase to conform the coding style introducing in **Milestone [3.4](https://github.com/mozilla/nightlytt/issues?milestone=3&state=closed)**.

Fix should address the following
- 2 char indentation
  use
  
  ```
  var myObject = {
    memberFunction1: function (aParam) {
      doSomething();
    },
  
    memberFunction1: function (aParam) {
      doAnything();
    }
  }
  ```
  
  instead of 
  
  ```
  var myObject = {
  memberFunction1: function (aParam) {
    doSomething();
  },
  
  memberFunction1: function (aParam) {
    doAnything();
  }
  }
  ```
- space between `function` and the opening `(` bracket
  use
  
  ```
  function () {
    ...
  ```
  
  instead of
  
  ```
  function() {
    ...
  ```
- left brace `{` at end of first line
  use
  
  ```
  function (aParam) {
    ...
  ```
  
  instead of
  
  ```
  function (aParam)
  {
    ...
  ```
- _named function expressions?_
  Please vote!
  For example [Coding Style](https://developer.mozilla.org/En/Mozilla_Coding_Style_Guide#Methods_and_functions) says
  
  > Methods should use the named function expression syntax so that stack traces read better
- `a`-prefixed function parameters
  name your params
  
  ```
  function doIt(aElement, aIndex, aArray) {
    ...
  ```
  
  instead of
  
  ```
  function doIt(element, index, array) {
    ...
  ```

Feel free to comment, I will update the above list!

Source: [review](https://github.com/mozilla/nightlytt/pull/74/#discussion_r966106) [comments](https://github.com/mozilla/nightlytt/pull/76/#discussion_r965941)

**Comment by whimboo** [comment]
With the rewrite all old code is gone.
