### ISSUE TITLE
Implement nttAddonManager.jsm - an AddonManager / Extension Manager wrapper

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#90]
This is an issue [based on the talk](https://github.com/mozilla/nightlytt/pull/89#issuecomment-6417336) in #89:

**whimboo** commented

> At the same time I would like to see that we make use of your new ExtensionManager class over on pull #85.

**xabolcs** commented

> Even we could implement an `nttAddonManager.jsm` which simply imports `AddonManager.jsm` if exists or uses
> an `AddonManagerImpl()` / `ExtensionManagerImpl()` inside and exports that as `AddonManager`.
> Hm?
> With that module we could do easily:
> 
> ```
>    Cu.import("resource://nightly/modules/nttAddonManager.jsm");
>    AddonManager.someFunction(aParam, aCallback);
> ```
> 
> Thoughts?

**whimboo** commented

> Sounds great. Lets do that.

**Comment by whimboo** [comment]
Not necessary anymore after the rewrite.
