### ISSUE TITLE
Could be hidecolumnpicker controlled programatically?

### ISSUE THREAD

**Issue by xabolcs** [mozilla/nightlytt#92]
Find it out!

This issue is [based on the talk](https://github.com/mozilla/nightlytt/pull/74#discussion_r966123) in #74

**whimboo** commented

> Personally I would say we should remove hidecolumnpicker="true" and let the user decide which columns he is interested in.

**xabolcs** commented

> As talked on IRC, will leave this attribute as is.
> If there is a way to control the value of `hidecolumnpicker` programatically then a follow-up issue could be filed.

**Comment by whimboo** [comment]
The code doesn't exist anymore, and I think a feature like this would be overkill.
